use std::fs;

use agent_loop::Feedback;
use anyhow::{Context, Result};
use tracing::debug;

use crate::phase::Phase;
use crate::run::RunConfig;
use crate::ui;

pub struct PromptfooEvals;

impl Phase for PromptfooEvals {
    fn id(&self) -> u8 {
        3
    }
    fn name(&self) -> &'static str {
        "Promptfoo Evals"
    }

    fn run(&self, config: &RunConfig) -> Result<()> {
        let feedback_path = config.working_dir.join("feedback.json");

        if !feedback_path.exists() {
            ui::warn(format!(
                "No feedback.json at {} — complete phase 2 first.",
                ui::path_str(&feedback_path)
            ));
            return Ok(());
        }

        let feedback: Feedback = serde_json::from_str(
            &fs::read_to_string(&feedback_path).context("reading feedback.json")?,
        )
        .context("parsing feedback.json")?;

        debug!(clusters = feedback.clusters.len(), "loaded feedback");

        let mut yaml = String::from(
            "# Generated by ail\n\
             # Run: promptfoo eval --config <this file> --output eval-results.json\n\n\
             description: \"AIL phase 3 baseline\"\n\n\
             prompts:\n\
             \x20\x20- |\n\
             \x20\x20\x20\x20Cluster: {{cluster_id}}\n\
             \x20\x20\x20\x20Type: {{cluster_type}}\n\
             \x20\x20\x20\x20Severity: {{severity}}\n\
             \x20\x20\x20\x20Evidence: {{evidence_count}}\n\
             \x20\x20\x20\x20Diagnosis: {{diagnosis}}\n\
             \x20\x20\x20\x20Sample: {{sample}}\n\n\
             providers:\n\
             \x20\x20- echo\n\n\
             tests:\n",
        );

        for cluster in &feedback.clusters {
            yaml.push_str(&format!(
                "# --- cluster: {} ({:?})\n\
                 # severity: {:?}  evidence: {}\n",
                cluster.id, cluster.cluster_type, cluster.severity, cluster.evidence_count,
            ));
            push_yaml_comment(&mut yaml, &cluster.diagnosis);
            yaml.push_str("# sample:\n");
            push_yaml_comment(&mut yaml, &cluster.sample);
            yaml.push('\n');
            yaml.push_str("  - vars:\n");
            push_yaml_literal(&mut yaml, 6, "cluster_id", &cluster.id);
            push_yaml_literal(
                &mut yaml,
                6,
                "cluster_type",
                &format!("{:?}", cluster.cluster_type),
            );
            push_yaml_literal(&mut yaml, 6, "severity", &format!("{:?}", cluster.severity));
            yaml.push_str(&format!(
                "      evidence_count: {}\n",
                cluster.evidence_count
            ));
            push_yaml_literal(&mut yaml, 6, "diagnosis", &cluster.diagnosis);
            push_yaml_literal(&mut yaml, 6, "sample", &cluster.sample);
            yaml.push('\n');
        }

        let evals_path = config.working_dir.join("evals.yaml");

        if config.dry_run {
            ui::dry_run(format!(
                "write {} cluster evals to {}",
                feedback.clusters.len(),
                ui::path_str(&evals_path)
            ));
            return Ok(());
        }

        fs::write(&evals_path, &yaml)?;
        ui::success(format!(
            "eval template ({} clusters) → {}",
            feedback.clusters.len(),
            ui::path_str(&evals_path)
        ));
        ui::info(format!(
            "Edit then run: {}",
            ui::code(format!(
                "promptfoo eval --config {} --output {}",
                evals_path.display(),
                config.working_dir.join("eval-results.json").display()
            ))
        ));

        Ok(())
    }
}

fn push_yaml_comment(yaml: &mut String, value: &str) {
    if value.is_empty() {
        yaml.push_str("#\n");
        return;
    }

    for line in value.lines() {
        yaml.push_str("# ");
        yaml.push_str(line);
        yaml.push('\n');
    }
}

fn push_yaml_literal(yaml: &mut String, indent: usize, key: &str, value: &str) {
    let prefix = " ".repeat(indent);
    yaml.push_str(&format!("{prefix}{key}: |-\n"));

    if value.is_empty() {
        yaml.push_str(&format!("{prefix}  \n"));
        return;
    }

    for line in value.lines() {
        yaml.push_str(&prefix);
        yaml.push_str("  ");
        yaml.push_str(line);
        yaml.push('\n');
    }
}
