use std::fs;

use agent_loop::Feedback;
use anyhow::{Context, Result};

use crate::run::RunConfig;

pub fn run(config: &RunConfig) -> Result<()> {
    let feedback_path = config.working_dir.join("feedback.json");

    if !feedback_path.exists() {
        println!("No feedback.json — complete phase 2 first.");
        return Ok(());
    }

    let feedback: Feedback =
        serde_json::from_str(&fs::read_to_string(&feedback_path).context("reading feedback.json")?)
            .context("parsing feedback.json")?;

    // Generate a promptfoo eval template per cluster
    let mut yaml = String::from(
        "# Generated by ail — edit before running\n\
         # Run: promptfoo eval --config <this file> --output eval-results.json\n\n",
    );

    for cluster in &feedback.clusters {
        yaml.push_str(&format!(
            "# --- cluster: {} ({:?})\n\
             # severity: {:?}  evidence: {}\n\
             # {}\n\
             # sample: {}\n\n",
            cluster.id,
            cluster.cluster_type,
            cluster.severity,
            cluster.evidence_count,
            cluster.diagnosis,
            cluster.sample,
        ));
    }

    let evals_path = config.working_dir.join("evals.yaml");

    if config.dry_run {
        println!(
            "[dry-run] would write {} cluster evals to {}",
            feedback.clusters.len(),
            evals_path.display()
        );
        return Ok(());
    }

    fs::write(&evals_path, &yaml)?;
    println!(
        "Wrote eval template ({} clusters) → {}",
        feedback.clusters.len(),
        evals_path.display()
    );
    println!(
        "\nEdit then run:\n  promptfoo eval --config {} --output {}",
        evals_path.display(),
        config.working_dir.join("eval-results.json").display()
    );

    Ok(())
}
