use std::fs;

use agent_loop::Feedback;
use anyhow::{Context, Result};
use tracing::debug;

use crate::phase::Phase;
use crate::run::RunConfig;
use crate::ui;

// TODO(test/integration): add integration test for phase 3 — plant a feedback.json fixture,
// run execute() starting at phase 3, assert evals.yaml is written and contains one comment
// block per cluster
pub struct PromptfooEvals;

impl Phase for PromptfooEvals {
    fn id(&self) -> u8 {
        3
    }
    fn name(&self) -> &'static str {
        "Promptfoo Evals"
    }

    fn run(&self, config: &RunConfig) -> Result<()> {
        let feedback_path = config.working_dir.join("feedback.json");

        if !feedback_path.exists() {
            ui::warn(format!(
                "No feedback.json at {} — complete phase 2 first.",
                ui::path_str(&feedback_path)
            ));
            return Ok(());
        }

        let feedback: Feedback = serde_json::from_str(
            &fs::read_to_string(&feedback_path).context("reading feedback.json")?,
        )
        .context("parsing feedback.json")?;

        debug!(clusters = feedback.clusters.len(), "loaded feedback");

        let mut yaml = String::from(
            "# Generated by ail — edit before running\n\
             # Run: promptfoo eval --config <this file> --output eval-results.json\n\n",
        );

        for cluster in &feedback.clusters {
            yaml.push_str(&format!(
                "# --- cluster: {} ({:?})\n\
                 # severity: {:?}  evidence: {}\n\
                 # {}\n\
                 # sample: {}\n\n",
                cluster.id,
                cluster.cluster_type,
                cluster.severity,
                cluster.evidence_count,
                cluster.diagnosis,
                cluster.sample,
            ));
        }

        let evals_path = config.working_dir.join("evals.yaml");

        if config.dry_run {
            ui::dry_run(format!(
                "write {} cluster evals to {}",
                feedback.clusters.len(),
                ui::path_str(&evals_path)
            ));
            return Ok(());
        }

        fs::write(&evals_path, &yaml)?;
        ui::success(format!(
            "eval template ({} clusters) → {}",
            feedback.clusters.len(),
            ui::path_str(&evals_path)
        ));
        ui::info(format!(
            "Edit then run: {}",
            ui::code(format!(
                "promptfoo eval --config {} --output {}",
                evals_path.display(),
                config.working_dir.join("eval-results.json").display()
            ))
        ));

        Ok(())
    }
}
